#!/usr/bin/env python3

import sys
import rospy
from stretch_moveit_shim.srv import SetJoints, SetJointsRequest, SetBodyResponse
from stretch_moveit_shim.msg import Joint

rospy.wait_for_service('/stretch_interface/set_joints')

while(True):
    print("Press Enter:")
    text = input()
    if len(text) == 0:
        try:
            service = rospy.ServiceProxy('/stretch_interface/set_joints', SetJoints)
            msg = Joint(joint_name='joint_lift', val = 0.8)
            service([msg])
        except rospy.ServiceException as e:
            print("Service call failed: %s"%e)

    print("\nPress Enter:")
    text = input()
    if len(text) == 0:
        try:
            service = rospy.ServiceProxy('/stretch_interface/set_joints', SetJoints)
            msg = Joint(joint_name='joint_lift', val = 0.4)
            service([msg])
        except rospy.ServiceException as e:
            print("Service call failed: %s"%e)